name: Run on Windows

on: push

jobs:
  windows_job:
    runs-on: windows-latest

    steps:
      - name: Print Windows message
        run: echo "Running on Windows runner!"

      - name: Show directory
        run: dir

      - name: Show system info
        run: systeminfo
